server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Routes

#Course
spring.cloud.gateway.routes[0].id=COURSE-POST-SERVICE
spring.cloud.gateway.routes[0].uri=lb://COURSE-POST-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/update/courses/**

spring.cloud.gateway.routes[1].id=COURSE-GET-SERVICE
spring.cloud.gateway.routes[1].uri=lb://COURSE-GET-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/read/courses/**

# Teacher
spring.cloud.gateway.routes[2].id=TEACHER-GET-SERVICE
spring.cloud.gateway.routes[2].uri=lb://TEACHER-GET-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/read/teachers/**

spring.cloud.gateway.routes[3].id=TEACHER-COMMAND-SERVICE
spring.cloud.gateway.routes[3].uri=lb://TEACHER-COMMAND-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/update/teachers/**

# User
spring.cloud.gateway.routes[4].id=USER-GET-SERVICE
spring.cloud.gateway.routes[4].uri=lb://USER-GET-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/read/users/**

spring.cloud.gateway.routes[5].id=USER-POST-SERVICE
spring.cloud.gateway.routes[5].uri=lb://USER-POST-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/update/users/**

# Enrollment
spring.cloud.gateway.routes[6].id=ENROLLMENT-GET-SERVICE
spring.cloud.gateway.routes[6].uri=lb://ENROLLMENT-GET-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/find/enrollments/**

spring.cloud.gateway.routes[7].id=ENROLLMENT-POST-SERVICE
spring.cloud.gateway.routes[7].uri=lb://ENROLLMENT-POST-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/update/enrollments/**