spring.datasource.url=jdbc:postgresql://localhost:5432/enrollment-service-db
spring.datasource.username=postgres
spring.datasource.password=100919

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=505013