spring.datasource.url=jdbc:postgresql://localhost:5432/enrollment-service-db
spring.datasource.username=postgres
spring.datasource.password=100919

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=50513

spring.application.name=ENROLLMENT-GET-SERVICE
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/